### ISSUE TITLE
Module does not get data for ^DJI

### ISSUE THREAD

**Issue by kwaaak** [Eiken/yahoofinance#3]
Errors with

> TypeError: non-empty format string passed to object.\_\_format\_\_

 because `latest, percentage, currency` are `None`

**Comment by kwaaak** [comment]
Just the error handling: https://github.com/Eiken/yahoofinance/compare/master...kwaaak:patch-1

**Comment by Eiken** [comment]
This works fine now with both DJI and ^DJI
